### ISSUE TITLE
MGrid component's GetId function should call different property name, not Id. 

### ISSUE THREAD

**Issue by theilgaz** [manureini/MComponents#10]
There are many developers using Id as an PK int. This is a common usage for relational database tables. I suggest you to change reserved Id property (as a Guid) to RowId or something like this. 

In SQL Server there is a hidden row_id column for specifying unique line.

**Comment by manureini** [comment]
Yes you are right. The usage of the id is not really a nice way in the grid.
I removed it in version 1.3.3. The Grid will now use the object itself instead the id to determine the selected row etc.
Can you test if these changes are working for you?
